# html lang
language: en

# main menu navigation
menu:
  文章: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/yoyo.css

# scripts loaded in the end of the body
scripts:
- /js/velocity.ui.min.js
- /js/yoyo.js
- /js/scroll.js
