language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "CanvinHuang"
  - git config user.email "943866180@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - curl -X POST http://fix.zukmb.cn/deploy/nd97zE9QAm0TWkdRUGbGMuSQnPYYK7OAJxUsKx8PwYiBcifBbff0lAMBN1ir -d 'reason=Update docs&branch=master&update_only=true&source=Travis CI'
# E: Build LifeCycle

branches:
  only:
    - blog-resource
env:
 global:
   - GH_REF: github.com/CavinHuang/CavinHuang.github.io.git
